version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: fdm_mongodb_prod
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_prod:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fdm_community
    networks:
      - fdm_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fdm_backend_prod
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - NODE_ENV=production
    networks:
      - fdm_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fdm_frontend_prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    networks:
      - fdm_network

networks:
  fdm_network:
    driver: bridge

volumes:
  mongodb_data_prod:
    driver: local