version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: fdm_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fdm_community
    networks:
      - fdm_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fdm_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    volumes:
      - ./backend:/app
    networks:
      - fdm_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fdm_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fdm_network

networks:
  fdm_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local